/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/gdWDS0N73M8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Card } from "@/components/ui/card"

export function Admin() {
  return (
    <div className="flex flex-col w-full min-h-screen">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <Link className="flex items-center gap-2 text-lg font-semibold sm:text-base mr-4" href="#">
          <BugIcon className="w-6 h-6" />
          <span>Accessibility Violations</span>
        </Link>
        <nav className="hidden font-medium sm:flex flex-row items-center gap-5 text-sm lg:gap-6">
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Dashboard
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Violations
          </Link>
          <Link className="font-bold" href="#">
            Reports
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Settings
          </Link>
        </nav>
        <div className="flex items-center w-full gap-4 md:ml-auto md:gap-2 lg:gap-4">
          <form className="flex-1 ml-auto sm:flex-initial">
            <div className="relative">
              <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
              <Input
                className="pl-8 sm:w-[300px] md:w-[200px] lg:w-[300px]"
                placeholder="Search violations..."
                type="search"
              />
            </div>
          </form>
          <Button className="rounded-full" size="icon" variant="ghost">
            <img
              alt="Avatar"
              className="rounded-full"
              height="32"
              src="/placeholder.svg"
              style={{
                aspectRatio: "32/32",
                objectFit: "cover",
              }}
              width="32"
            />
            <span className="sr-only">Toggle user menu</span>
          </Button>
        </div>
      </header>
      <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] bg-gray-100/40 flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10 dark:bg-gray-800/40">
        <div className="max-w-6xl w-full mx-auto grid gap-2">
          <div className="flex items-center justify-between">
            <h1 className="font-semibold text-3xl">Accessibility Violations</h1>
            <div className="flex items-center text-sm gap-2">
              <div className="text-gray-500 flex items-center gap-2 dark:text-gray-400">
                <span className="inline-block w-2 h-2 bg-[#09CE6B] rounded-full animate-ping duration-[5000]" />
                123 violations
              </div>
              <Separator className="h-5" orientation="vertical" />
              <div className="text-gray-500 flex items-center gap-2 dark:text-gray-400">
                <CircleAlertIcon className="w-4 h-4 text-red-500" />
                12 high priority
              </div>
              <Separator className="h-5" orientation="vertical" />
              <div className="text-gray-500 flex items-center gap-2 dark:text-gray-400">
                <TriangleAlertIcon className="w-4 h-4 text-yellow-500" />
                45 medium priority
              </div>
              <Separator className="h-5" orientation="vertical" />
              <div className="text-gray-500 flex items-center gap-2 dark:text-gray-400">
                <InfoIcon className="w-4 h-4 text-blue-500" />
                66 low priority
              </div>
            </div>
          </div>
          <Card className="p-0 overflow-hidden">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Page URL</TableHead>
                  <TableHead>Violation Type</TableHead>
                  <TableHead>Description</TableHead>
                  <TableHead>Priority</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell>
                    <Link className="font-medium" href="#">
                      /home
                    </Link>
                  </TableCell>
                  <TableCell>Missing alt text</TableCell>
                  <TableCell>Image on the homepage does not have an alt text description.</TableCell>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      <CircleAlertIcon className="w-4 h-4 text-red-500" />
                      High
                    </div>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>
                    <Link className="font-medium" href="#">
                      /pricing
                    </Link>
                  </TableCell>
                  <TableCell>Contrast ratio</TableCell>
                  <TableCell>The text on the pricing page has insufficient contrast ratio.</TableCell>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      <TriangleAlertIcon className="w-4 h-4 text-yellow-500" />
                      Medium
                    </div>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>
                    <Link className="font-medium" href="#">
                      /about
                    </Link>
                  </TableCell>
                  <TableCell>Keyboard navigation</TableCell>
                  <TableCell>The about page is not fully navigable using the keyboard.</TableCell>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      <InfoIcon className="w-4 h-4 text-blue-500" />
                      Low
                    </div>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>
                    <Link className="font-medium" href="#">
                      /contact
                    </Link>
                  </TableCell>
                  <TableCell>Form labeling</TableCell>
                  <TableCell>The contact form fields are not properly labeled for screen readers.</TableCell>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      <TriangleAlertIcon className="w-4 h-4 text-yellow-500" />
                      Medium
                    </div>
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell>
                    <Link className="font-medium" href="#">
                      /blog
                    </Link>
                  </TableCell>
                  <TableCell>Heading structure</TableCell>
                  <TableCell>The blog page does not have a proper heading structure.</TableCell>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      <InfoIcon className="w-4 h-4 text-blue-500" />
                      Low
                    </div>
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </Card>
        </div>
      </main>
    </div>
  )
}

function BugIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 2 1.88 1.88" />
      <path d="M14.12 3.88 16 2" />
      <path d="M9 7.13v-1a3.003 3.003 0 1 1 6 0v1" />
      <path d="M12 20c-3.3 0-6-2.7-6-6v-3a4 4 0 0 1 4-4h4a4 4 0 0 1 4 4v3c0 3.3-2.7 6-6 6" />
      <path d="M12 20v-9" />
      <path d="M6.53 9C4.6 8.8 3 7.1 3 5" />
      <path d="M6 13H2" />
      <path d="M3 21c0-2.1 1.7-3.9 3.8-4" />
      <path d="M20.97 5c0 2.1-1.6 3.8-3.5 4" />
      <path d="M22 13h-4" />
      <path d="M17.2 17c2.1.1 3.8 1.9 3.8 4" />
    </svg>
  )
}


function CircleAlertIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <line x1="12" x2="12" y1="8" y2="12" />
      <line x1="12" x2="12.01" y1="16" y2="16" />
    </svg>
  )
}


function InfoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function TriangleAlertIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3" />
      <path d="M12 9v4" />
      <path d="M12 17h.01" />
    </svg>
  )
}
