/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ysAKxghaLoZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Interactiveqanda() {
  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <div className="space-y-2">
        <h2 className="text-3xl font-bold">Interactive Q&A</h2>
        <p className="text-gray-500 dark:text-gray-400">Answer the questions below and submit your responses.</p>
      </div>
      <div className="space-y-4">
        <div>
          <div>
            <div>
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <h3 className="text-lg font-medium">What is your favorite color?</h3>
                  <div className="text-gray-500 dark:text-gray-400 text-sm">1 of 3</div>
                </div>
                <div className="space-y-2">
                  <Input placeholder="Enter your favorite color" />
                </div>
              </div>
            </div>
            <div>
              <Button className="mr-2" disabled variant="outline">
                Previous
              </Button>
              <Button>Next</Button>
            </div>
          </div>
          <div>
            <div>
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <h3 className="text-lg font-medium text-gray-500 dark:text-gray-400">What is your dream job?</h3>
                  <div className="text-gray-500 dark:text-gray-400 text-sm">2 of 3</div>
                </div>
                <div className="space-y-2">
                  <Input placeholder="Enter your dream job" />
                </div>
              </div>
            </div>
            <div>
              <Button className="mr-2" variant="outline">
                Previous
              </Button>
              <Button>Next</Button>
            </div>
          </div>
          <div>
            <div>
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <h3 className="text-lg font-medium text-gray-500 dark:text-gray-400">What is your favorite book?</h3>
                  <div className="text-gray-500 dark:text-gray-400 text-sm">3 of 3</div>
                </div>
                <div className="space-y-2">
                  <Input placeholder="Enter your favorite book" />
                </div>
              </div>
            </div>
            <div>
              <Button className="mr-2" variant="outline">
                Previous
              </Button>
              <Button>Submit</Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
